version: '3.6'
services:
  app:
    image: ${REPOSITORY_URI}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    container_name: app
    ports:
      - ${PORT}:${PORT}
    tty: true