version: '3.6'
services:
  app:
    image: ${REPOSITORY_URI}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    container_name: app
    ports:
      - 8080:8080
    tty: true